# Generated by Django 5.1.7 on 2025-05-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siswa', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
